// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
public class Suite1ChromeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void S1() {
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.manage().window().setSize(new Dimension(550, 696));
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("TODO:"));
    driver.findElement(By.cssSelector("p")).click();
  }
  @Test
  public void S2() {
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.manage().window().setSize(new Dimension(1453, 925));
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.cssSelector("h2")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Яйца, которые впечатляют своим размером"));
    driver.findElement(By.linkText("Отзывы")).click();
    driver.findElement(By.cssSelector(".review:nth-child(1) > p")).click();
    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    assertThat(driver.findElement(By.cssSelector(".review:nth-child(1) strong")).getText(), is("— Алексей, повар"));
  }
  @Test
  public void S3() {
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.manage().window().setSize(new Dimension(1453, 925));
    driver.findElement(By.cssSelector("h2")).click();
    assertThat(driver.findElement(By.cssSelector("h2 > span:nth-child(3)")).getText(), is("НАСТОЯЩИЙ РАЗМЕР"));
    driver.findElement(By.linkText("ГНЕЗДО")).click();
    driver.findElement(By.linkText("РАЗМЕРЫ")).click();
    driver.findElement(By.linkText("ЗАБРАТЬ")).click();
    driver.findElement(By.cssSelector(".btn-hype:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".hero")).click();
    driver.findElement(By.cssSelector(".social-icon:nth-child(1)")).click();
  }
  @Test
  public void S4() {
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.manage().window().setSize(new Dimension(1453, 925));
    driver.findElement(By.cssSelector(".container:nth-child(4)")).click();
    assertThat(driver.findElement(By.cssSelector(".word-3")).getText(), is("ЗНАЧЕНИЕ"));
    driver.findElement(By.linkText("О ФЕРМЕ")).click();
  }
  @Test
  public void S5() {
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    driver.get("https://xn----8sbbqoikx1fp7b1b.xn--p1ai/");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("preloader")));
    }
    driver.manage().window().setSize(new Dimension(1453, 925));
    try {
      Thread.sleep(5000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.linkText("БОЛЬШИЕ ЯЙЦА"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(4) > a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("li:nth-child(4) > a")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,4808)");
  }
}



